#!/usr/bin/env python3
"""Download free hosted YouTube captions directly into figure packages."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.parse import parse_qs, urlencode, urlparse
from urllib.request import Request, urlopen


VIDEO_ID = re.compile(r"^[A-Za-z0-9_-]{11}$")
FIGURE_TARGET = re.compile(r"^[a-z0-9-]+/[a-z0-9-]+$")
LANGUAGE = re.compile(r"^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$")
TIMESTAMP = re.compile(r"^\[(?:(\d+):)?(\d{1,2}):(\d{2})\]\s*(.*)$")
INVALID_FILENAME = re.compile(r"[<>:\"/\\|?*\x00-\x1f]")
VIDEO_ID_METADATA = re.compile(r"(?m)^- Video ID:\s*([A-Za-z0-9_-]{11})\s*$")

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_FIGURES_ROOT = REPOSITORY_ROOT / "figures"
DEFAULT_CACHE_ROOT = Path(__file__).resolve().parent / ".cache"


class TranscriptError(RuntimeError):
    """A requested transcript could not be safely retrieved or written."""


@dataclass(frozen=True)
class Segment:
    text: str
    start: float
    duration: float

    @property
    def end(self) -> float:
        return self.start + self.duration


@dataclass(frozen=True)
class VideoMetadata:
    title: str
    channel: str


@dataclass(frozen=True)
class DownloadResult:
    video_id: str
    status: str
    path: Path | None = None
    message: str = ""
    title: str = ""
    channel: str = ""


def extract_video_id(value: str) -> str:
    value = value.strip()
    if VIDEO_ID.fullmatch(value):
        return value

    parsed = urlparse(value if "://" in value else f"https://{value}")
    host = (parsed.hostname or "").lower().removeprefix("www.")
    candidate = ""
    if host in {"youtube.com", "m.youtube.com", "music.youtube.com"}:
        if parsed.path == "/watch":
            candidate = parse_qs(parsed.query).get("v", [""])[0]
        else:
            parts = [part for part in parsed.path.split("/") if part]
            if len(parts) >= 2 and parts[0] in {"shorts", "embed", "live"}:
                candidate = parts[1]
    elif host == "youtu.be":
        candidate = parsed.path.lstrip("/").split("/")[0]

    if not VIDEO_ID.fullmatch(candidate):
        raise ValueError(f"Cannot extract a valid YouTube video ID from {value!r}")
    return candidate


def parse_hosted_transcript(text: str, video_id: str) -> list[Segment]:
    if text.lstrip().startswith("# No captions available"):
        raise TranscriptError(f"No captions are available for {video_id}")

    starts: list[float] = []
    blocks: list[list[str]] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        match = TIMESTAMP.match(line)
        if match:
            hours = int(match.group(1) or 0)
            minutes = int(match.group(2))
            seconds = int(match.group(3))
            if (minutes >= 60 and match.group(1) is not None) or seconds >= 60:
                raise TranscriptError(f"Hosted response has an invalid timestamp for {video_id}")
            starts.append(hours * 3600 + minutes * 60 + seconds)
            blocks.append([match.group(4).strip()])
        elif blocks and line and not line.startswith("--- Generated by"):
            blocks[-1].append(line)

    if not starts:
        raise TranscriptError(f"Hosted response contained no timestamped transcript for {video_id}")
    if any(current < previous for previous, current in zip(starts, starts[1:])):
        raise TranscriptError(f"Hosted response timestamps are out of order for {video_id}")

    segments: list[Segment] = []
    for index, (start, lines) in enumerate(zip(starts, blocks)):
        segment_text = " ".join(" ".join(lines).split())
        segment_text = segment_text.split(" --- Generated by ", 1)[0].rstrip()
        if not segment_text:
            continue
        next_start = starts[index + 1] if index + 1 < len(starts) else start + 5
        segments.append(Segment(segment_text, start, max(1.0, next_start - start)))
    if not segments:
        raise TranscriptError(f"Hosted response contained no caption text for {video_id}")
    return segments


def timestamp(seconds: float) -> str:
    total = max(0, int(seconds))
    return f"{total // 3600:02d}:{(total % 3600) // 60:02d}:{total % 60:02d}"


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


class HostedTranscriptClient:
    def __init__(self, cache_root: Path = DEFAULT_CACHE_ROOT) -> None:
        self.cache_root = cache_root

    def fetch_captions(
        self, video_id: str, language: str, *, refresh: bool = False
    ) -> list[Segment]:
        cache_path = self.cache_root / "captions" / f"{video_id}.{language}.txt"
        if cache_path.is_file() and not refresh:
            return parse_hosted_transcript(cache_path.read_text(encoding="utf-8"), video_id)

        query = urlencode({"lang": language})
        url = f"https://youtube-transcript.ai/transcript/{video_id}.txt?{query}"
        text = self._request(url).decode("utf-8")
        segments = parse_hosted_transcript(text, video_id)
        atomic_write(cache_path, text)
        return segments

    def fetch_metadata(self, video_id: str, *, refresh: bool = False) -> VideoMetadata:
        cache_path = self.cache_root / "metadata" / f"{video_id}.json"
        if cache_path.is_file() and not refresh:
            data = json.loads(cache_path.read_text(encoding="utf-8"))
        else:
            watch_url = f"https://www.youtube.com/watch?v={video_id}"
            query = urlencode({"url": watch_url, "format": "json"})
            data = json.loads(self._request(f"https://www.youtube.com/oembed?{query}"))
            atomic_write(cache_path, json.dumps(data, ensure_ascii=False, indent=2) + "\n")

        title = str(data.get("title", "")).strip()
        channel = str(data.get("author_name", "")).strip()
        if not title:
            raise TranscriptError(f"YouTube metadata contained no title for {video_id}")
        return VideoMetadata(title=title, channel=channel or "Unknown")

    @staticmethod
    def _request(url: str) -> bytes:
        request = Request(
            url,
            headers={"User-Agent": "swing-thing-transcripts/1.0 (+personal research archive)"},
        )
        try:
            with urlopen(request, timeout=30) as response:
                return response.read()
        except HTTPError as error:
            detail = error.read().decode("utf-8", errors="replace").strip()
            raise TranscriptError(f"HTTP {error.code}: {detail or error.reason}") from error
        except URLError as error:
            raise TranscriptError(f"Network error: {error.reason}") from error


def resolve_figure(target: str, figures_root: Path) -> Path:
    if not FIGURE_TARGET.fullmatch(target):
        raise ValueError("Figure must use the form <style>/<figure-id>")
    root = figures_root.resolve()
    figure = (root / target).resolve()
    try:
        figure.relative_to(root)
    except ValueError as error:
        raise ValueError("Figure target escapes the figures directory") from error
    if not figure.is_dir() or not (figure / "figure.ts").is_file():
        raise ValueError(f"Unknown figure package: {target}")
    return figure


def read_figure_name(figure: Path) -> str:
    source = (figure / "figure.ts").read_text(encoding="utf-8")
    match = re.search(r'"name"\s*:\s*("(?:[^"\\]|\\.)*")', source)
    if not match:
        raise TranscriptError(f"Cannot find the canonical figure name in {figure / 'figure.ts'}")
    return str(json.loads(match.group(1)))


def find_existing_transcript(figure: Path, video_id: str) -> Path | None:
    matches: list[Path] = []
    transcripts = figure / "transcripts"
    if not transcripts.is_dir():
        return None
    for path in transcripts.glob("*.md"):
        content = path.read_text(encoding="utf-8", errors="replace")
        metadata = VIDEO_ID_METADATA.search(content)
        if metadata and metadata.group(1) == video_id:
            matches.append(path)
    if len(matches) > 1:
        raise TranscriptError(
            f"Multiple transcripts for {video_id}: {', '.join(str(path) for path in matches)}"
        )
    return matches[0] if matches else None


def sanitize_filename(value: str, max_length: int = 100) -> str:
    value = INVALID_FILENAME.sub("-", value).strip(" .")
    value = re.sub(r"\s+", " ", value) or "untitled"
    return value[:max_length].rstrip(" .")


def title_destination(figure: Path, title: str, video_id: str) -> Path:
    transcripts = figure / "transcripts"
    candidate = transcripts / f"{sanitize_filename(title)}.md"
    if not candidate.exists():
        return candidate
    fallback = transcripts / f"{sanitize_filename(title, 84)} - {video_id}.md"
    if fallback.exists():
        raise TranscriptError(f"A different transcript already occupies {fallback}")
    return fallback


def render_transcript(
    *,
    figure_name: str,
    metadata: VideoMetadata,
    video_id: str,
    language: str,
    segments: list[Segment],
    retrieved_at: datetime,
) -> str:
    canonical_url = f"https://www.youtube.com/watch?v={video_id}"
    lines = [
        f"# {figure_name}",
        "",
        f"- Video: {metadata.title}",
        f"- Channel: {metadata.channel}",
        f"- URL: {canonical_url}",
        f"- Video ID: {video_id}",
        f"- Transcript language: {language}",
        "- Caption type: hosted captions",
        f"- Transcript start: {timestamp(segments[0].start)}",
        f"- Transcript end: {timestamp(segments[-1].end)}",
        "- Coverage: full available transcript",
        f"- Retrieved at: {retrieved_at.astimezone(timezone.utc).isoformat()}",
        "",
        "> This file contains every timestamped segment returned by the free hosted caption "
        "provider. The provider's source may still be incomplete, and automatically generated "
        "captions may contain errors.",
        "",
        "## Full transcript",
        "",
    ]
    lines.extend(f"[{timestamp(segment.start)}] {segment.text}" for segment in segments)
    return "\n".join(lines) + "\n"


def download_one(
    *,
    url: str,
    figure: Path,
    language: str,
    client: HostedTranscriptClient,
    overwrite: bool = False,
    title: str | None = None,
    channel: str | None = None,
    title_filename: bool = False,
    now: datetime | None = None,
) -> DownloadResult:
    video_id = extract_video_id(url)
    existing = find_existing_transcript(figure, video_id)
    if existing and not overwrite:
        return DownloadResult(video_id, "unchanged", existing, "already present")

    segments = client.fetch_captions(video_id, language, refresh=overwrite)
    metadata_warning = ""
    remote_metadata: VideoMetadata | None = None
    if title is None or channel is None:
        try:
            remote_metadata = client.fetch_metadata(video_id, refresh=overwrite)
        except (OSError, ValueError, json.JSONDecodeError, TranscriptError) as error:
            metadata_warning = f"; metadata unavailable: {error}"
    metadata = VideoMetadata(
        title=title or (remote_metadata.title if remote_metadata else f"YouTube video {video_id}"),
        channel=channel or (remote_metadata.channel if remote_metadata else "Unknown"),
    )

    destination = existing or (
        title_destination(figure, metadata.title, video_id)
        if title_filename
        else figure / "transcripts" / f"{video_id} - {sanitize_filename(metadata.title)}.md"
    )
    content = render_transcript(
        figure_name=read_figure_name(figure),
        metadata=metadata,
        video_id=video_id,
        language=language,
        segments=segments,
        retrieved_at=now or datetime.now(timezone.utc),
    )
    atomic_write(destination, content)
    return DownloadResult(
        video_id,
        "written",
        destination,
        metadata_warning.lstrip("; "),
        metadata.title,
        metadata.channel,
    )


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(
        description="Download free hosted YouTube captions into a Swing Thing figure package."
    )
    result.add_argument("urls", nargs="+", metavar="YOUTUBE_URL")
    result.add_argument("--figure", required=True, help="Target as <style>/<figure-id>")
    result.add_argument("--figures", type=Path, default=DEFAULT_FIGURES_ROOT)
    result.add_argument("--cache", type=Path, default=DEFAULT_CACHE_ROOT)
    result.add_argument("--language", default="en")
    result.add_argument("--overwrite", action="store_true")
    result.add_argument("--title", help="Override the title when downloading exactly one URL")
    result.add_argument("--channel", help="Override the channel when downloading exactly one URL")
    result.add_argument(
        "--title-filename",
        action="store_true",
        help="Name new files from the public video title instead of prefixing the video ID",
    )
    result.add_argument("--json", action="store_true", help=argparse.SUPPRESS)
    return result


def result_payload(result: DownloadResult) -> dict[str, str | None]:
    return {
        "videoId": result.video_id,
        "status": result.status,
        "path": str(result.path) if result.path else None,
        "filename": result.path.name if result.path else None,
        "message": result.message,
        "title": result.title,
        "channel": result.channel,
    }


def main(argv: list[str] | None = None) -> int:
    args = parser().parse_args(argv)
    if not LANGUAGE.fullmatch(args.language):
        print(f"ERROR: Invalid language code: {args.language!r}", file=sys.stderr)
        return 2
    if (args.title or args.channel) and len(args.urls) != 1:
        print("ERROR: --title and --channel can only be used with one URL", file=sys.stderr)
        return 2
    try:
        figure = resolve_figure(args.figure, args.figures)
    except ValueError as error:
        if args.json:
            print(json.dumps({"results": [], "error": str(error)}))
        else:
            print(f"ERROR: {error}", file=sys.stderr)
        return 2

    client = HostedTranscriptClient(args.cache)
    written = unchanged = failed = 0
    results: list[dict[str, str | None]] = []
    for url in args.urls:
        try:
            result = download_one(
                url=url,
                figure=figure,
                language=args.language,
                client=client,
                overwrite=args.overwrite,
                title=args.title,
                channel=args.channel,
                title_filename=args.title_filename,
            )
            results.append(result_payload(result))
            if result.status == "written":
                written += 1
                if not args.json:
                    print(f"WROTE {result.video_id}: {result.path}")
                if result.message and not args.json:
                    print(f"WARN {result.video_id}: {result.message}", file=sys.stderr)
            else:
                unchanged += 1
                if not args.json:
                    print(f"SKIP {result.video_id}: {result.path} ({result.message})")
        except (OSError, ValueError, json.JSONDecodeError, TranscriptError) as error:
            failed += 1
            results.append({
                "videoId": "",
                "status": "failed",
                "path": None,
                "filename": None,
                "message": str(error),
                "title": "",
                "channel": "",
            })
            if not args.json:
                print(f"FAILED {url}: {error}", file=sys.stderr)

    if args.json:
        print(json.dumps({
            "results": results,
            "written": written,
            "unchanged": unchanged,
            "failed": failed,
        }))
    else:
        print(f"Written: {written}")
        print(f"Unchanged: {unchanged}")
        print(f"Failed: {failed}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
