from __future__ import annotations

import importlib.util
import io
import json
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from datetime import datetime, timezone
from pathlib import Path


MODULE_PATH = Path(__file__).with_name("download_transcripts.py")
SPEC = importlib.util.spec_from_file_location("download_transcripts", MODULE_PATH)
assert SPEC and SPEC.loader
DOWNLOADER = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = DOWNLOADER
SPEC.loader.exec_module(DOWNLOADER)


class FakeClient:
    def __init__(self) -> None:
        self.caption_calls: list[tuple[str, str, bool]] = []
        self.metadata_calls: list[tuple[str, bool]] = []

    def fetch_captions(self, video_id: str, language: str, *, refresh: bool = False):
        self.caption_calls.append((video_id, language, refresh))
        return [
            DOWNLOADER.Segment("First caption", 2, 4),
            DOWNLOADER.Segment("Second caption", 6, 5),
        ]

    def fetch_metadata(self, video_id: str, *, refresh: bool = False):
        self.metadata_calls.append((video_id, refresh))
        return DOWNLOADER.VideoMetadata('A Lesson: "Circle"', "Laura Glaess")


class NetworkClient(DOWNLOADER.HostedTranscriptClient):
    def __init__(self, cache_root: Path) -> None:
        super().__init__(cache_root)
        self.requests: list[str] = []

    def _request(self, url: str) -> bytes:
        self.requests.append(url)
        if "oembed" in url:
            return b'{"title": "Lindy Circle", "author_name": "Teacher"}'
        return b"[0:02] First\n[0:06] Second\n"


class TranscriptDownloaderTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        self.figures = self.root / "figures"
        self.figure = self.figures / "lindy" / "lindy-circle"
        self.figure.mkdir(parents=True)
        (self.figure / "figure.ts").write_text(
            'export default { "move": { "id": "lindy-circle", "name": "Lindy Circle" } };\n',
            encoding="utf-8",
        )

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def test_extracts_supported_youtube_url_shapes(self):
        video_id = "P083vG0JKB8"
        values = [
            video_id,
            f"https://www.youtube.com/watch?v={video_id}&feature=share",
            f"youtu.be/{video_id}?si=abc",
            f"https://youtube.com/shorts/{video_id}",
            f"https://m.youtube.com/embed/{video_id}",
            f"https://youtube.com/live/{video_id}",
        ]

        self.assertEqual(
            [DOWNLOADER.extract_video_id(value) for value in values],
            [video_id] * len(values),
        )

    def test_rejects_non_youtube_and_malformed_urls(self):
        for value in ("https://example.com/watch?v=P083vG0JKB8", "youtube.com/watch?v=short"):
            with self.subTest(value=value), self.assertRaises(ValueError):
                DOWNLOADER.extract_video_id(value)

    def test_parses_multiline_hosted_transcript_and_drops_provider_footer(self):
        text = (
            "[0:02] First line\ncontinued here\n"
            "[01:03] Second line --- Generated by https://youtube-transcript.ai "
            "Interactive version\n"
        )

        segments = DOWNLOADER.parse_hosted_transcript(text, "P083vG0JKB8")

        self.assertEqual([segment.start for segment in segments], [2, 63])
        self.assertEqual(segments[0].text, "First line continued here")
        self.assertEqual(segments[1].text, "Second line")

    def test_rejects_missing_or_out_of_order_caption_segments(self):
        with self.assertRaises(DOWNLOADER.TranscriptError):
            DOWNLOADER.parse_hosted_transcript("# No captions available", "P083vG0JKB8")
        with self.assertRaises(DOWNLOADER.TranscriptError):
            DOWNLOADER.parse_hosted_transcript(
                "[0:10] Later\n[0:05] Earlier\n", "P083vG0JKB8"
            )

    def test_resolves_only_existing_two_part_figure_targets(self):
        self.assertEqual(
            DOWNLOADER.resolve_figure("lindy/lindy-circle", self.figures),
            self.figure.resolve(),
        )
        for target in ("lindy", "../outside", "lindy/unknown", "/absolute/figure"):
            with self.subTest(target=target), self.assertRaises(ValueError):
                DOWNLOADER.resolve_figure(target, self.figures)

    def test_download_writes_deterministic_auditable_markdown(self):
        client = FakeClient()
        retrieved_at = datetime(2026, 7, 17, 12, 30, tzinfo=timezone.utc)

        result = DOWNLOADER.download_one(
            url="https://youtu.be/P083vG0JKB8",
            figure=self.figure,
            language="en",
            client=client,
            now=retrieved_at,
        )

        self.assertEqual(result.status, "written")
        assert result.path
        self.assertEqual(result.path.name, "P083vG0JKB8 - A Lesson- -Circle-.md")
        content = result.path.read_text(encoding="utf-8")
        self.assertIn("# Lindy Circle", content)
        self.assertIn('- Video: A Lesson: "Circle"', content)
        self.assertIn("- Channel: Laura Glaess", content)
        self.assertIn("- Video ID: P083vG0JKB8", content)
        self.assertIn("- Transcript end: 00:00:11", content)
        self.assertIn("[00:00:02] First caption", content)
        self.assertEqual(client.caption_calls, [("P083vG0JKB8", "en", False)])

    def test_studio_mode_names_new_transcript_from_video_title(self):
        result = DOWNLOADER.download_one(
            url="https://youtu.be/P083vG0JKB8",
            figure=self.figure,
            language="en",
            client=FakeClient(),
            title_filename=True,
        )

        assert result.path
        self.assertEqual(result.path.name, "A Lesson- -Circle-.md")
        self.assertEqual(result.title, 'A Lesson: "Circle"')
        self.assertEqual(result.channel, "Laura Glaess")

    def test_title_filename_uses_video_id_when_title_is_already_taken(self):
        transcripts = self.figure / "transcripts"
        transcripts.mkdir()
        (transcripts / "A Lesson- -Circle-.md").write_text("different video\n", encoding="utf-8")

        result = DOWNLOADER.download_one(
            url="https://youtu.be/P083vG0JKB8",
            figure=self.figure,
            language="en",
            client=FakeClient(),
            title_filename=True,
        )

        assert result.path
        self.assertEqual(result.path.name, "A Lesson- -Circle- - P083vG0JKB8.md")

    def test_repeat_download_skips_existing_video_without_network_calls(self):
        transcripts = self.figure / "transcripts"
        transcripts.mkdir()
        existing = transcripts / "legacy-name.md"
        existing.write_text("# Figure\n\n- Video ID: P083vG0JKB8\n", encoding="utf-8")
        client = FakeClient()

        result = DOWNLOADER.download_one(
            url="P083vG0JKB8",
            figure=self.figure,
            language="en",
            client=client,
        )

        self.assertEqual(result.status, "unchanged")
        self.assertEqual(result.path, existing)
        self.assertEqual(client.caption_calls, [])
        self.assertEqual(client.metadata_calls, [])

    def test_json_cli_reports_an_existing_transcript_without_network(self):
        transcripts = self.figure / "transcripts"
        transcripts.mkdir()
        existing = transcripts / "Original title.md"
        existing.write_text("# Figure\n\n- Video ID: P083vG0JKB8\n", encoding="utf-8")
        output = io.StringIO()

        with redirect_stdout(output):
            status = DOWNLOADER.main([
                "--figures", str(self.figures),
                "--figure", "lindy/lindy-circle",
                "--json",
                "--title-filename",
                "https://youtu.be/P083vG0JKB8",
            ])

        payload = json.loads(output.getvalue())
        self.assertEqual(status, 0)
        self.assertEqual(payload["unchanged"], 1)
        self.assertEqual(payload["results"][0]["filename"], "Original title.md")

    def test_overwrite_refreshes_and_preserves_existing_filename(self):
        transcripts = self.figure / "transcripts"
        transcripts.mkdir()
        existing = transcripts / "01 - Existing.md"
        existing.write_text("# Figure\n\n- Video ID: P083vG0JKB8\n", encoding="utf-8")
        client = FakeClient()

        result = DOWNLOADER.download_one(
            url="P083vG0JKB8",
            figure=self.figure,
            language="en",
            client=client,
            overwrite=True,
        )

        self.assertEqual(result.path, existing)
        self.assertEqual(client.caption_calls, [("P083vG0JKB8", "en", True)])
        self.assertEqual(client.metadata_calls, [("P083vG0JKB8", True)])
        self.assertIn("## Full transcript", existing.read_text(encoding="utf-8"))

    def test_client_uses_ignored_cache_before_remote_provider(self):
        client = NetworkClient(self.root / "cache")

        first = client.fetch_captions("P083vG0JKB8", "en")
        second = client.fetch_captions("P083vG0JKB8", "en")
        metadata_first = client.fetch_metadata("P083vG0JKB8")
        metadata_second = client.fetch_metadata("P083vG0JKB8")

        self.assertEqual(first, second)
        self.assertEqual(metadata_first, metadata_second)
        self.assertEqual(len(client.requests), 2)
        self.assertIn("youtube-transcript.ai/transcript/P083vG0JKB8.txt", client.requests[0])
        self.assertIn("youtube.com/oembed", client.requests[1])

    def test_metadata_failure_still_writes_caption_transcript(self):
        class MetadataFailingClient(FakeClient):
            def fetch_metadata(self, video_id: str, *, refresh: bool = False):
                raise DOWNLOADER.TranscriptError("metadata unavailable")

        result = DOWNLOADER.download_one(
            url="P083vG0JKB8",
            figure=self.figure,
            language="en",
            client=MetadataFailingClient(),
        )

        assert result.path
        self.assertIn("metadata unavailable", result.message)
        self.assertIn("- Video: YouTube video P083vG0JKB8", result.path.read_text(encoding="utf-8"))

    def test_independent_metadata_override_keeps_remote_title(self):
        result = DOWNLOADER.download_one(
            url="P083vG0JKB8",
            figure=self.figure,
            language="en",
            client=FakeClient(),
            channel="Curated channel name",
        )

        assert result.path
        content = result.path.read_text(encoding="utf-8")
        self.assertIn('- Video: A Lesson: "Circle"', content)
        self.assertIn("- Channel: Curated channel name", content)


if __name__ == "__main__":
    unittest.main()
